FROM jenkins/jenkins:lts-jdk17

USER root

RUN apt-get update && apt-get install -y \
    curl wget git unzip docker.io \
    && rm -rf /var/lib/apt/lists/*

# Maven stable (OFFICIAL MIRROR OK)
ENV MAVEN_VERSION=3.9.9

RUN curl -fsSL https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
    | tar -xz -C /opt/ \
    && ln -s /opt/apache-maven-${MAVEN_VERSION} /opt/maven

ENV MAVEN_HOME=/opt/maven
ENV PATH=$MAVEN_HOME/bin:$PATH

# Docker access
RUN groupadd -f docker && usermod -aG docker jenkins

USER jenkins