FROM jenkins/jenkins:lts-jdk17

USER root

# ===== Dépendances =====
RUN apt-get update && apt-get install -y \
    wget \
    curl \
    unzip \
    apt-transport-https \
    ca-certificates \
    gnupg \
    lsb-release

# ===== Maven =====
ENV MAVEN_VERSION=3.9.11

RUN wget https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz && \
    tar -xzf apache-maven-${MAVEN_VERSION}-bin.tar.gz -C /opt && \
    ln -s /opt/apache-maven-${MAVEN_VERSION}/bin/mvn /usr/bin/mvn && \
    rm apache-maven-${MAVEN_VERSION}-bin.tar.gz

# ===== Docker CLI =====
RUN curl -fsSL https://get.docker.com | sh

# ===== permissions Jenkins =====
RUN usermod -aG docker jenkins

USER jenkins

# check versions
RUN mvn -version
RUN docker --version