management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.mvc.pathmatch.use-suffix-pattern=true
spring.mvc.pathmatch.use-registered-suffix-pattern=true
